language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@^5.7.1 # We always want npm 5.7 for the `ci` command
  - npm ci

script:
  - npm test
  - npm run lint